### ISSUE TITLE
Microphone doesn't work on MacOS Monterey, missing permission, work around included.

### ISSUE THREAD

**Issue by bhyde** [jerrod-lankford/google-voice-desktop-app#106] opened 2022-03-08 23:50 UTC
Sadly nobody I called could hear me.  Puzzled out that this was because the application didn't have the right to use microphone. It needs permission from the user to listen in on his life.

I found two workarounds.

1) If the user runs the application from the command line.
```shell
/Applications/Voice\ Desktop.app/Contents/MacOS/Voice\ Desktop
```
It will then ask for permission when the time comes.  Bummer is, you have to do this every time.

2) The user can hand modify the user's "Transparency, Consent, and Control" settings.  [Here is a little gist](https://gist.github.com/bhyde/1e4b90fb1fb9f8bc14371a28ce86a815) to do just that.

Obviously, in a more perfect world the Application would deal with this.

**Comment by justdave** [comment] 2022-03-25 20:33
Having this same issue on Big Sur as well.

The command line approach appears to work because the app is then a child process of the Terminal, and the Terminal appears to know how to ask permission. (The prompt that comes up asks if it's okay for the Terminal to access your microphone).

**Comment by justdave** [comment] 2022-03-25 20:38
This looks like a duplicate of #101

**Closed** 2022-04-30 11:46 UTC

**Comment by bhyde** [comment] 2022-05-22 14:00
Thanks, worked for me.  And yeah, I cleared the permission during the upgrade.
