### ISSUE TITLE
White window after coming back from "sleep"

### ISSUE THREAD

**Issue by Bwangster12** [jerrod-lankford/google-voice-desktop-app#51] opened 2021-04-05 12:41 UTC
If I leave the app open and put my SLEEP, when I come back the entire window is white and there it doesn't refresh or give me an option to refresh or reload it.  I have to exit the app and re-open.

**Comment by jeffjensen** [comment] 2021-04-05 12:42
I confirm the same issue.

**Comment by costacola** [comment] 2021-04-05 13:27
+1 here as well

**Comment by latin-programmer** [comment] 2021-04-10 17:10
Happens to me too. I just close and restart to work around for now. That is my top list of pull requests to contribute if at least make it so that we can "refresh" manually with keystrokes or context menus without shutting down the app.

**Comment by AceRoehrborn** [comment] 2021-04-10 17:38
I also have this issue.  I am a field service tech and am frequently connecting to networks that don't have internet, or hopping around between networks with varying IP addresses some with internet and some without.  This white window seems to happen when I am moving between networks.  Perhaps the issue is related to lack of network(internet) connectivity and not so much related to sleep???

**Comment by latin-programmer** [comment] 2021-04-11 17:24
@AceRoehrborn You might be getting close to an answer there. This looks to be an Electron issue and the word out there is that it is possibly related to unexpected errors. See:
https://github.com/electron/electron/issues/2357

They have a workaround posted but it has had limited success. Also sounds like later versions may fix it. Did you upgrade to 1.1.6? We upgraded to the latest version of Electron there.

**Comment by FormallyKnownAs** [comment] 2021-04-13 12:31
I also have this issue.  What's really interesting is on the Mac, there's an update to force refresh the browser which fixes the bug.  So it sounds like a problem with the browser session...?

**Comment by AceRoehrborn** [comment] 2021-04-21 15:12
> @AceRoehrborn You might be getting close to an answer there. This looks to be an Electron issue and the word out there is that it is possibly related to unexpected errors. See:
> [electron/electron#2357](https://github.com/electron/electron/issues/2357)
> 
> They have a workaround posted but it has had limited success. Also sounds like later versions may fix it. Did you upgrade to 1.1.6? We upgraded to the latest version of Electron there.

I have noticed the issue still exists on 1.1.7 for me.  It happened this morning and was not a network switching/no internet issue. I was in the office all day yesterday and the computer just went to sleep as I went home and back to the office this morning.  White screen this morning with no refresh.  

Quit from the tray and restart resolved it.

I updated to 1.1.8 this morning and will report back if I continue to notice the issue.

**Comment by alpenandrew** [comment] 2021-05-01 20:49
I get this even if the computer hasn't slept and I don't the network has changed. Usually happens after long periods of inactivity on the computer

**Comment by wickedfable** [comment] 2021-07-29 20:35
Mine seems to be a bit random as to when it happens. I've had it go for hours where I'm not doing anything and come back and it works fine. Other times, I'm actively doing work on my computer and try to check my notifications and I just get a white screen (probably within 30 minutes or so of opening the program). I have not been able to pin down anything in particular on my end that causes it to occur. Definitely just close the program and reopening it temporarily solves the issue, so not a huge deal at the moment, but would be nice to not have to do that, of course.

**Comment by reesericci** [comment] 2021-09-12 01:26
same issue here

**Comment by dahainsworth** [comment] 2021-11-13 12:58
this is still happening to me pretty much every day.  quit/restart fixes it but i often forget so can sometimes miss a text or two thinking it is running.  going to look into if a windows automatic task can stop and restart the program occasionally.    i suspect as latin-programmer pointed out that the electron renderer has crashed due to network not being up as it comes up from sleep or similar.   i'd be happy to test any debug code if that could help.   the app is fantastic except for this single bug for me.  so hoping it can get some love.

**Comment by eFail** [comment] 2022-01-08 23:47
Rejoice.  I believe I've finally got a fool-proof fix for this: https://github.com/jerrod-lankford/google-voice-desktop-app/pull/95

**Closed** 2022-01-11 17:36 UTC

**Comment by wickedfable** [comment] 2022-02-19 01:31
I was thinking it was just me, but another person in my household and myself are both experiencing this issue still after installing 1.2.8. I still get the blank white screen but also one where the whole app except for the top menu bar freezes, requiring me to reload the app. Sometimes reloading just seems to kill the app entirely and I have to open it up again. It also seems a lot more frequent than with past versions. I find myself having to manually reload the app often - I'm not sure if it does ever reload by itself as it supposed to happen.

**Comment by eFail** [comment] 2022-02-19 05:48
I'm continuing to investigate this issue, but the reduced frequency in which it's occurring now on my machine has made it difficult to debug.

**Comment by MadLittleMods** [comment] 2022-09-16 03:24
For reference, I don't use this desktop app but I do use the web version https://voice.google.com/, and it often goes blank and unresponsive in Chrome where I have to kill the tab and reload the page to get it working again.

Perhaps it's related since it looks like the desktop app is embedding the web version and Electron is Chromium based.

The closest thing I have found online are the following threads but stumbled upon this issue because the PR to fix this, https://github.com/jerrod-lankford/google-voice-desktop-app/pull/95, was referenced from https://github.com/vector-im/element-desktop/issues/680 which I do follow out of curiousity,

 - https://www.reddit.com/r/Googlevoice/comments/lpqzzu/memory_leak_in_voicegooglecom/
 - https://www.reddit.com/r/Googlevoice/comments/hys76n/google_voice_constant_crashing_in_browsers/
 - https://www.reddit.com/r/Googlevoice/comments/hsfl3v/google_voice_hogging_computer_resources/
